 
version: '3.8'

services:
 postgres: 
     image: postgres:15
     container_name: postgres
     restart: always
     environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
     ports:
      - "${POSTGRES_PORT}:5432"
     volumes:
      - postgres_data:/var/lib/postgresql/data
 app:
     build:
      context: .
      dockerfile: Dockerfile
     ports:
      - "${APP_PORT}:3000"
     restart: always
     environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
     volumes:
      - .:/app
      - /app/node_modules
     depends_on:
      - postgres
volumes:
  postgres_data:
 
    

